### PR TITLE
Fixed Sonarqube (#253)

### LINKED ISSUE #253: Fix Sonarqube Vulnerabilities and Code Smells
https://sonarcloud.io/dashboard?id=E-Edu_task

### PR DESCRIPTION
**Pull request by PAException**

### CODE REVIEW

File: src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java [hunk 1]
```diff
@@ -46,6 +48,54 @@
...
+
+	public TaskModel updateLanguage(String language) {
+		if (Validation.validateNotNullOrEmpty(language) && !language.equals(this.language))
+			this.language = language;
+
+		return this;
+	}
+
+	public TaskModel updateLecture(ControllerResult<LectureModel> lectureResult) {
+		if (lectureResult.isResultPresent() && lectureResult.getResult().equals(this.lectureId))
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java]: Would this ever work?!

File: src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java [hunk 2]
```diff
@@ -70,7 +120,6 @@ public TaskResponseDTO toResponseDTO() {
 	 * @return a new {@link TaskModel} instance
 	 */
 	public static TaskModel create(int taskId) {
-		//TODO: ObjectPool
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java]: Why do u remove IMPORTANT TODOs?!

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/FreestyleSolutionEndpoint.java [hunk 3]
```diff
@@ -22,7 +22,6 @@
 
 	@Autowired private FreestyleSolutionController freestyleSolutionController;
 
-	//TODO: Just teacher access
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/FreestyleSolutionEndpoint.java]: Why

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/ImageSolutionEndpoint.java [hunk 4]
```diff
@@ -22,7 +22,6 @@
 
 	@Autowired private ImageSolutionController imageSolutionController;
 
-	//TODO: Just teacher access
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/ImageSolutionEndpoint.java]: Why

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/MultipleChoiceSolutionEndpoint.java [hunk 5]
```diff
@@ -35,7 +35,7 @@ public Object getMultipleChoiceSolution(@PathVariable @Min(1) int taskId) {
 		return this.multipleChoiceSolutionController.getMultipleChoiceSolution(taskId).getHttpResponse();
 	}
 
-	@GetMapping("/solution/multiple_choice/{task_id}/all")//TODO: Just for teachers
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/MultipleChoiceSolutionEndpoint.java]: Why

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/TopicConnectionSolutionEndpoint.java [hunk 6]
```diff
@@ -35,7 +35,7 @@ public Object getTopicConnectionSolution(@PathVariable @Min(1) int taskId) {
 		return this.topicConnectionSolutionController.getTopicConnectionSolution(taskId).getHttpResponse();
 	}
 
-	@GetMapping("/solution/topic_connection/{taskId}/all") //TODO: Just teacher have permission
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/TopicConnectionSolutionEndpoint.java]: Why

File: src/main/java/de/themorpheus/edu/taskservice/pubsub/PubSubService.java [hunk 7]
```diff
@@ -22,7 +22,7 @@
 public class PubSubService {
 
 	@Value("${spring.redis.enabled}")
-	public static boolean ENABLED;
+	public static boolean enabled;
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/pubsub/PubSubService.java]: nah, then just make it private and use getters

File: src/main/java/de/themorpheus/edu/taskservice/pubsub/sub/api/ObjectSubscriber.java [hunk 8]
```diff
@@ -25,13 +25,13 @@
...
 	@PostConstruct
 	default void registerSubscription() {
-		if (!PubSubService.ENABLED) return;
+		if (!PubSubService.enabled) return;
 		this.getMessageListenerContainer().addMessageListener(this, this.getTopics().get(this.getMessageClass()));
 	}
 
 	@Override
 	default void receive(Message message) {
-		Object obj = this.getRedisTemplate().getValueSerializer().deserialize(message.getBody()); //TODO: Can we check the type before deserialization?
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/pubsub/sub/api/ObjectSubscriber.java]: Why

File: src/main/java/de/themorpheus/edu/taskservice/spring/RestControllerExceptionHandler.java [hunk 9]
```diff
@@ -11,11 +11,11 @@
 @RestControllerAdvice
 public class RestControllerExceptionHandler extends ResponseEntityExceptionHandler {
 
-	private static final Logger LOGGER = LoggerFactory.getLogger(RestControllerExceptionHandler.class.getSimpleName());
+	private static final Logger EXCEPTION_LOGGER = LoggerFactory.getLogger(RestControllerExceptionHandler.class.getSimpleName());
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/spring/RestControllerExceptionHandler.java]: Nope, tha's NOT an exception logger, it's a fcking casual logger!

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 10]
```diff
@@ -8,34 +8,61 @@
 
 		public static final String NAME_KEY = "difficulty";
 
+		private Difficulty() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 11]
```diff
@@ -8,34 +8,61 @@
...
+		}
+
 	}
 
 	public static class Lecture {
 
 		public static final String NAME_KEY = "lecture";
 
+		private Lecture() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 12]
```diff
@@ -8,34 +8,61 @@
...
+		}
+
 	}
 
 	public static class Module {
 
 		public static final String NAME_KEY = "module";
 
+		private Module() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 13]
```diff
@@ -8,34 +8,61 @@
...
+		}
+
 	}
 
 	public static class Task {
 
 		public static final String NAME_KEY = "task";
 
-		public static class TaskDone {
+		private Task() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 14]
```diff
@@ -8,34 +8,61 @@
...
+		}
+
+		public static class Voting {
+
+			public static final String NAME_KEY = "task_voting";
+
+			private Voting() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 15]
```diff
@@ -8,34 +8,61 @@
...
+			}
+
+		}
+
+		public static class Done {
 
 			public static final String NAME_KEY = "task_done";
 
+			private Done() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 16]
```diff
@@ -44,38 +71,50 @@
 
 		public static final String NAME_KEY = "task_group";
 
+		private TaskGroup() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 17]
```diff
@@ -44,38 +71,50 @@
...
 	public static class TaskType {
 
 		public static final String NAME_KEY = "task_type";
 
-	}
-
-	public static class TaskVoting {
-
-		public static final String NAME_KEY = "task_voting";
+		private TaskType() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 18]
```diff
@@ -44,38 +71,50 @@
...
+		}
 
 	}
 
 	public static class Solution {
 
 		public static final String NAME_KEY = "solution";
 
+		private Solution() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 19]
```diff
@@ -44,38 +71,50 @@
...
+		}
+
 		public static class SimpleEquation {
 
 			public static final String NAME_KEY = "simple_equation_solution";
 
+			private SimpleEquation() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 20]
```diff
@@ -44,38 +71,50 @@
...
+			}
+
 		}
 
 		public static class Freestyle {
 
 			public static final String NAME_KEY = "freestyle_solution";
 
+			private Freestyle() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 21]
```diff
@@ -44,38 +71,50 @@
...
+			}
+
 			public static class UserSolutions {
 
 				public static final String NAME_KEY = "freestyle_solution_user";
 
+				private UserSolutions() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 22]
```diff
@@ -84,10 +123,16 @@
 
 			public static final String NAME_KEY = "image_solution";
 
+			private Image() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 23]
```diff
@@ -84,10 +123,16 @@
...
+			}
+
 			public static class UserSolutions {
 
 				public static final String NAME_KEY = "image_solution_user";
 
+				private UserSolutions() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 24]
```diff
@@ -96,28 +141,43 @@
 
 			public static final String NAME_KEY = "multiple_choice_solution";
 
+			private MultipleChoice() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 25]
```diff
@@ -96,28 +141,43 @@
...
+			}
+
 		}
 
 		public static class TopicConnection {
 
 			public static final String NAME_KEY = "topic_connection_solution";
 
+			private TopicConnection() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 26]
```diff
@@ -96,28 +141,43 @@
...
+			}
+
 		}
 
 		public static class Wordsalad {
 
 			public static final String NAME_KEY = "wordsalad_solution";
 
+			private Wordsalad() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 27]
```diff
@@ -96,28 +141,43 @@
...
 	}
 
 	public static class UserId {
 
-		public static final UUID TEST_UUID = UUID.fromString("52bd088c-d6ad-4cee-9f93-cabfc8c07234"); //TODO: use real userId
+		public static final UUID TEST_UUID = UUID.fromString("52bd088c-d6ad-4cee-9f93-cabfc8c07234");
 
 		public static final UUID EMPTY_UUID = UUID.fromString("00000000-0000-0000-0000-000000000000");
 
+		private UserId() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 28]
```diff
@@ -96,28 +141,43 @@
...
+			private Wordsalad() {
+			}
+
 		}
 
 	}
 
 	public static class UserId {
 
-		public static final UUID TEST_UUID = UUID.fromString("52bd088c-d6ad-4cee-9f93-cabfc8c07234"); //TODO: use real userId
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java:117]: Why

File: src/main/java/de/themorpheus/edu/taskservice/util/Constants.java [hunk 29]
```diff
@@ -96,28 +141,43 @@
...
+		public static final UUID TEST_UUID = UUID.fromString("52bd088c-d6ad-4cee-9f93-cabfc8c07234");
 
 		public static final UUID EMPTY_UUID = UUID.fromString("00000000-0000-0000-0000-000000000000");
 
+		private UserId() {
+		}
+
+	}
+
+	private Constants() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Constants.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/I18n.java [hunk 30]
```diff
@@ -12,4 +12,7 @@
 	public static final String WRONG_TYPE = "WRONG_TYPE";
 	public static final String FAILED_DEPENDENCY = "FAILED_DEPENDENCY";
 
+	private I18n() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/I18n.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

File: src/main/java/de/themorpheus/edu/taskservice/util/Validation.java [hunk 31]
```diff
@@ -2,6 +2,9 @@
 
 public class Validation {
 
+	private Validation() {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/util/Validation.java]: Use @NoArgsConstructor(AccessLevel.PRIVATE)

**Review by steve-hb — CHANGES_REQUESTED** [review]

File: src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java (hunk 1 above)
Comment (PAException) [reply src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java]: Why not?

Comment (steve-hb) [reply src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java]: You're checking whther the lecture you're getting is the same lecture in the task model, so this would never update

File: src/main/java/de/themorpheus/edu/taskservice/spring/RestControllerExceptionHandler.java [hunk 32]
```diff
@@ -11,11 +11,11 @@
 @RestControllerAdvice
 public class RestControllerExceptionHandler extends ResponseEntityExceptionHandler {
 
-	private static final Logger LOGGER = LoggerFactory.getLogger(RestControllerExceptionHandler.class.getSimpleName());
+	private static final Logger CASUAL_LOGGER = LoggerFactory.getLogger(RestControllerExceptionHandler.class.getSimpleName());
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/spring/RestControllerExceptionHandler.java]: that's not what I meant for sure...

**Review by steve-hb — CHANGES_REQUESTED** [review]

File: src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java (hunk 1 above)
Comment (PAException) [reply src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java]: ops

**Review by steve-hb — APPROVED** [review]
