### PR TITLE
Issue 144,235

### LINKED ISSUE #210: Wrong error code
https://github.com/E-Edu/task/blob/master/src/main/java/de/themorpheus/edu/taskservice/util/Error.java#L16

If an server side error occurs, the right response would be a generic "500" -> INTERNAL_ERROR or something like that

### LINKED ISSUE #235: Fix all thrown Errors

### PR DESCRIPTION
**Pull request by PAException**
Includes #144 
Closes #235 

I tested every route and adapted userData requests.

I also made the option that every nameKey can be the id

### CODE REVIEW

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java [hunk 1]
```diff
@@ -36,12 +41,22 @@ public Object getLectures() {
 
 	@GetMapping("/module/{moduleNameKey}/lecture")
 	public Object getLecturesFromModule(@PathVariable @NotBlank String moduleNameKey) {
-		return this.lectureController.getAllLecturesFromModule(moduleNameKey).getHttpResponse();
+		try {
+			int moduleId = Integer.parseInt(moduleNameKey);
+			return this.lectureController.getAllLecturesByModuleId(moduleId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java [hunk 2]
```diff
@@ -26,7 +26,12 @@ public Object createLecture(@RequestBody @Valid CreateLectureRequestDTO dto) {
 
 	@GetMapping("/lecture/{nameKey}")
 	public Object getLecture(@PathVariable @NotBlank String nameKey) {
-		return this.lectureController.getLectureByNameKey(nameKey).getHttpResponse();
+		try {
+			int lectureId = Integer.parseInt(nameKey);
+			return this.lectureController.getLecture(lectureId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
+			return this.lectureController.getLectureByNameKey(nameKey).getHttpResponse();
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java [hunk 3]
```diff
@@ -36,12 +41,22 @@ public Object getLectures() {
...
+		}
 	}
 
 	@DeleteMapping("/lecture/{nameKey}")
 	public Object deleteLecture(@PathVariable @NotBlank String nameKey) {
-		return this.lectureController.deleteLecture(nameKey).getHttpResponse();
+		try {
+			int lectureId = Integer.parseInt(nameKey);
+			return this.lectureController.deleteLecture(lectureId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java [hunk 4]
```diff
@@ -26,7 +26,12 @@ public Object createModule(@RequestBody @Valid CreateModuleRequestDTO dto) {
 
 	@GetMapping("/module/{nameKey}")
 	public Object getModule(@PathVariable @NotBlank String nameKey) {
-		return this.moduleController.getModuleByNameKey(nameKey).getHttpResponse();
+		try {
+			int moduleId = Integer.parseInt(nameKey);
+			return this.moduleController.getModule(moduleId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java [hunk 5]
```diff
@@ -36,12 +41,22 @@ public Object getModules() {
 
 	@GetMapping("/subject/{subjectNameKey}/module")
 	public Object getModulesFromSubject(@PathVariable @NotBlank String subjectNameKey) {
-		return this.moduleController.getAllModulesFromSubject(subjectNameKey).getHttpResponse();
+		try {
+			int subjectId = Integer.parseInt(subjectNameKey);
+			return this.moduleController.getAllModulesSubjectId(subjectId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java [hunk 6]
```diff
@@ -36,12 +41,22 @@ public Object getModules() {
...
+		}
 	}
 
 	@DeleteMapping("/module/{nameKey}")
 	public Object deleteModule(@PathVariable @NotBlank String nameKey) {
-		return this.moduleController.deleteModule(nameKey).getHttpResponse();
+		try {
+			int moduleId = Integer.parseInt(nameKey);
+			return this.moduleController.deleteModule(moduleId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java [hunk 7]
```diff
@@ -25,8 +25,13 @@ public Object createSubject(@RequestBody @Valid CreateSubjectRequestDTO dto) {
 	}
 
 	@GetMapping("/subject/{nameKey}")
-	public Object getSubject(@PathVariable @NotBlank String nameKey) {
-		return this.subjectController.getSubjectByNameKey(nameKey).getHttpResponse();
+	public Object getSubjectByNameKey(@PathVariable @NotBlank String nameKey) {
+		try {
+			int subjectId = Integer.parseInt(nameKey);
+			return this.subjectController.getSubject(subjectId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java [hunk 8]
```diff
@@ -36,7 +41,12 @@ public Object getSubjects() {
 
 	@DeleteMapping("/subject/{nameKey}")
 	public Object deleteSubject(@PathVariable @NotBlank String nameKey) {
-		return this.subjectController.deleteSubject(nameKey).getHttpResponse();
+		try {
+			int subjectId = Integer.parseInt(nameKey);
+			return this.subjectController.deleteSubject(subjectId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java [hunk 9]
```diff
@@ -36,17 +38,23 @@ public Object createTask(@RequestBody @Valid CreateTaskRequestDTO dto) {
 
 	@GetMapping("/lecture/{lectureNameKey}/task")
 	public Object getAllTasksFromLecture(@PathVariable @NotBlank String lectureNameKey, @RequestParam(required = false) boolean showBanned) {
-		return this.taskController.getTasksFromLecture(lectureNameKey, showBanned).getHttpResponse();
+		try {
+			int lectureId = Integer.parseInt(lectureNameKey);
+			return this.taskController.getTasksByLectureId(lectureId, showBanned).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java:44]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java [hunk 10]
```diff
@@ -26,7 +26,12 @@ public Object createTaskType(@RequestBody @Valid CreateTaskTypeRequestDTO dto) {
 
 	@GetMapping("/task_type/{nameKey}")
 	public Object getTaskType(@PathVariable @NotBlank String nameKey) {
-		return this.taskTypeController.getTaskType(nameKey).getHttpResponse();
+		try {
+			int taskTypeId = Integer.parseInt(nameKey);
+			return this.taskTypeController.getTaskType(taskTypeId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java]: No, Regex should avoid this

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java [hunk 11]
```diff
@@ -36,7 +41,12 @@ public Object getTaskTypes() {
 
 	@DeleteMapping("/task_type/{nameKey}")
 	public Object deleteTaskType(@PathVariable @NotBlank String nameKey) {
-		return this.taskTypeController.deleteTaskType(nameKey).getHttpResponse();
+		try {
+			int taskTypeId = Integer.parseInt(nameKey);
+			return this.taskTypeController.deleteTaskType(taskTypeId).getHttpResponse();
+		} catch (NumberFormatException ignored) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java]: No, Regex should avoid this

**Review by steve-hb — CHANGES_REQUESTED** [review]

**Review by steve-hb — APPROVED** [review]
