### PR TITLE
Fixed Error on task delete (#182)

### LINKED ISSUE #182: Exception when deleting a task
# Description 

java.sql.SQLException: Cannot delete or update a parent row: a foreign key constraint fails (`e-edu`.`task_solution`, CONSTRAINT `FK8ywv40mf67ahkkp3nsg726q4u` FOREIGN KEY (`taskId_taskId`) REFERENCES `task_task` (`taskId`))

# Suggestion

### PR DESCRIPTION
**Pull request by PAException**
Closes #182

### CODE REVIEW

File: src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java [hunk 1]
```diff
@@ -116,17 +117,19 @@
 		ControllerResult<DifficultyModel> difficultyResult = this.difficultyController
 			.getDifficultyByNameKey(dto.getDifficultyNameKey());
 
-		if (lectureResult.isResultPresent()) task.setLectureId(lectureResult.getResult());
-		if (taskTypeResult.isResultPresent()) task.setTaskTypeId(taskTypeResult.getResult());
-		if (difficultyResult.isResultPresent()) task.setDifficultyId(difficultyResult.getResult());
-		if (Validation.validateNotNullOrEmpty(dto.getTask())) task.setTask(dto.getTask());
-		if (Validation.greaterZero(dto.getNecessaryPoints())) task.setNecessaryPoints(dto.getNecessaryPoints());
+		if (lectureResult.isResultPresent()) optionalTask.get().setLectureId(lectureResult.getResult());
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java]: Only get once

File: src/main/java/de/themorpheus/edu/taskservice/controller/solution/SolutionController.java [hunk 2]
```diff
@@ -84,21 +80,8 @@ public void deleteSolution(SolutionModel solutionId) {
...
-			for (String interfaceName : interfaceNames) if (interfaceName.equals(Solution.class.getName())) return true;
-
-			return false;
-		});
-
-		for (BeanDefinition beanDefinition : provider.findCandidateComponents("de.themorpheus")) {
-			Class<?> clazz = Class.forName(beanDefinition.getBeanClassName());
-			solutionControllers.add((Solution) clazz.getDeclaredConstructor().newInstance());
-		}
+	protected static void registerGenericSolutionController(Solution solution) {
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/controller/solution/SolutionController.java]: Remove "protected", u are calling this via package-private

**Review by steve-hb — CHANGES_REQUESTED** [review]
