### PR TITLE
Wrapped nearly everything in DTOs (#189) / Changed all Validations fo…

### LINKED ISSUE #187: Task throws an Exception while accessing taskId=0
# Description 

The Application throws an Exception because of a request on a taskId that doesn't exists

# Suggestion

Everytime a taskId is used change @Min(0) to @Min(1)

### LINKED ISSUE #189: Wrap returning models in Endpoints in DTOs
# Description

Return DTOs instead of models of the database because of e.g. useless data

# Suggestion

### PR DESCRIPTION
**Pull request by PAException**
…r IDs from @Min(0) to @Min(1) (#187)

## Description

Closes #187 
Closes #189

### CODE REVIEW

File: src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java [hunk 1]
```diff
@@ -68,14 +65,16 @@
 		tasks.removeIf(tm -> finishedTaskIds.contains(tm.getTaskId())); //TODO: Use SQL query
 		if (tasks.isEmpty()) return ControllerResult.of(Error.NO_CONTENT, NAME_KEY);
 
-		return ControllerResult.of(tasks.get(RANDOM.nextInt(tasks.size())));
+		return ControllerResult.of(tasks.get((int) (Math.random() * tasks.size())));
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java]: Nope, this would be less efficient and more biased

**Review by steve-hb — CHANGES_REQUESTED** [review]

File: src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java [hunk 2]
```diff
@@ -70,9 +77,16 @@
...
+		freestyleSolution = this.freestyleSolutionRepository.save(freestyleSolution);
+
+		return ControllerResult.of(new UpdateFreestyleSolutionResponseDTO(
+				freestyleSolution.getFreestyleSolutionId(),
+				freestyleSolution.getSolution()
+				)
+		);
 	}
 
+	@Transactional
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java:89]: Why?

File: src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java [hunk 3]
```diff
@@ -69,9 +74,13 @@
...
 		ImageSolutionModel imageSolution = optionalImageSolution.get();
 		imageSolution.setUrl(dto.getUrl());
-		return ControllerResult.of(this.imageSolutionRepository.save(imageSolution));
+		imageSolution = this.imageSolutionRepository.save(imageSolution);
+
+		return ControllerResult.of(
+				new UpdateImageSolutionResponseDTO(imageSolution.getImageSolutionId(), imageSolution.getUrl()));
 	}
 
+	@Transactional
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java:83]: Why?

File: src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/VoteTaskResponseDTO.java [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+@Data
+@NoArgsConstructor
+@AllArgsConstructor
+public class VoteTaskResponseDTO {
+
+	@Min(1)
+	int votingModelId;
+
+	int value;
+	UUID userId;
```
Comment (steve-hb) [inline src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/VoteTaskResponseDTO.java]: Where are the accessors?

**Review by steve-hb — CHANGES_REQUESTED** [review]

File: src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java (hunk 3 above)
Comment (PAException) [reply src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java:83]: because hibernates needs to know if i call a mehtod where a model is used

File: src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java (hunk 2 above)
Comment (PAException) [reply src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java:89]: because hibernates needs to know if i call a mehtod where a model is used
otherwise it throws an exception

**Review by steve-hb — APPROVED** [review]
